name: Windows CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-2022
    strategy:
      fail-fast: false
      matrix:
        configuration: [Release, Debug]
    steps:
    - uses: actions/checkout@v4

    - name: Checkout RayTracedGL1
      run: git clone --branch quake-fsr31-support https://github.com/sdas234f23f/RayTracedGL1.git rtgl1

    - name: Build RayTracedGL1
      run: |
        cmake -S rtgl1 -B rtgl1/Build -G Ninja -DCMAKE_BUILD_TYPE=${{ matrix.configuration }}
        cmake --build rtgl1/Build

    - name: Build vkQuake
      run: |
        cmake -S . -B build -G Ninja -DCMAKE_BUILD_TYPE=${{ matrix.configuration }} -DRTGL1_SDK_PATH=${{ github.workspace }}/rtgl1
        cmake --build build

    - name: Upload vkQuake
      uses: actions/upload-artifact@v4
      with:
        name: vkQuake-${{ matrix.configuration }}
        path: |
            build/vkquake.exe
            build/*.dll
